# Generated by Django 5.0.6 on 2024-05-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='stat_juridique',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
