# Generated by Django 5.0.3 on 2024-04-24 22:30

from django.db import migrations

def add_predefined_categories(apps, schema_editor):
    Category = apps.get_model('categories', 'Category')
    predefined_categories = ['Health', 'Education', 'Environment', 'Children', 'Urgent']
    for category_name in predefined_categories:
        Category.objects.create(name=category_name)

def remove_predefined_categories(apps, schema_editor):
    Category = apps.get_model('categories', 'Category')
    predefined_categories = ['Health', 'Education', 'Environment', 'Children', 'Urgent']
    Category.objects.filter(name__in=predefined_categories).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_predefined_categories, reverse_code=remove_predefined_categories)
    ]


