# Generated by Django 5.0.6 on 2024-05-30 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dons', '0002_alter_don_user'),
        ('publications', '0001_initial'),
        ('users', '0004_pendingemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='don',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dons', to='users.association'),
        ),
        migrations.AddField(
            model_name='don',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='don',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dons', to='publications.publication'),
        ),
    ]
