# Generated by Django 5.0.4 on 2024-05-16 18:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=150)),
                ('contenu', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=20)),
                ('association', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.association')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
        ),
    ]
